/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as DayDayRouteImport } from './routes/day.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayRoute = DayDayRouteImport.update({
  id: '/day/$day',
  path: '/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/proof': typeof ProofRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/proof': typeof ProofRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/proof': typeof ProofRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/proof'
    | '/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenge'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/proof'
    | '/day/$day'
  id:
    | '__root__'
    | '/'
    | '/challenge'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/proof'
    | '/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeRoute: typeof ChallengeRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProofRoute: typeof ProofRoute
  DayDayRoute: typeof DayDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$day': {
      id: '/day/$day'
      path: '/day/$day'
      fullPath: '/day/$day'
      preLoaderRoute: typeof DayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeRoute: ChallengeRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProofRoute: ProofRoute,
  DayDayRoute: DayDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
